import React from 'react';
import { Text, StyleSheet } from 'react-native';
import theme from "../theme";

const AkademikIcons = ({ name, style }) => {
    const icons = {
        "kimlik": "\ue800",
        "academia": "\ue803",
        "academia-square": "\ue804",
        "acclaim": "\ue805",
        "acclaim-square": "\ue806",
        "acm": "\ue807",
        "acmdl": "\ue808",
        "acmdl-square": "\ue809",
        "acm-square": "\ue80a",
        "ads": "\ue80b",
        "ads-square": "\ue80c",
        "africarxiv": "\ue80d",
        "africarxiv-square": "\ue80e",
        "archive": "\ue80f",
        "archive-square": "\ue810",
        "arxiv": "\ue811",
        "arxiv-square": "\ue812",
        "biorxiv": "\ue813",
        "biorxiv-square": "\ue814",
        "ceur": "\ue815",
        "ceur-square": "\ue816",
        "ciencia-vitae": "\ue817",
        "ciencia-vitae-square": "\ue818",
        "clarivate": "\ue819",
        "clarivate-square": "\ue81a",
        "closed-access": "\ue81b",
        "closed-access-square": "\ue81c",
        "conversation": "\ue81d",
        "conversation-square": "\ue81e",
        "coursera": "\ue81f",
        "coursera-square": "\ue820",
        "crossref": "\ue821",
        "crossref-square": "\ue822",
        "cv": "\ue823",
        "cv-square": "\ue824",
        "datacite": "\ue825",
        "datacite-square": "\ue826",
        "dataverse": "\ue827",
        "dataverse-square": "\ue828",
        "dblp": "\ue829",
        "dblp-square": "\ue82a",
        "depsy": "\ue82b",
        "depsy-square": "\ue82c",
        "doi": "\ue82d",
        "doi-square": "\ue82e",
        "dryad": "\ue82f",
        "dryad-square": "\ue830",
        "elsevier": "\ue831",
        "elsevier-square": "\ue832",
        "figshare": "\ue833",
        "figshare-square": "\ue834",
        "google-scholar": "\ue835",
        "google-scholar-square": "\ue836",
        "hal": "\ue837",
        "hal-square": "\ue838",
        "hypothesis": "\ue839",
        "hypothesis-square": "\ue83a",
        "ideas-repec": "\ue83b",
        "ideas-repec-square": "\ue83c",
        "ieee": "\ue83d",
        "ieee-square": "\ue83e",
        "impactstory": "\ue83f",
        "impactstory-square": "\ue840",
        "inaturalist": "\ue841",
        "inaturalist-square": "\ue842",
        "inpn": "\ue843",
        "inpn-square": "\ue844",
        "inspire": "\ue845",
        "inspire-square": "\ue846",
        "isidore": "\ue847",
        "isidore-square": "\ue848",
        "isni": "\ue849",
        "isni-square": "\ue84a",
        "jstor": "\ue84b",
        "jstor-square": "\ue84c",
        "lattes": "\ue84d",
        "lattes-square": "\ue84e",
        "mathoverflow": "\ue84f",
        "mathoverflow-square": "\ue850",
        "mendeley": "\ue851",
        "mendeley-square": "\ue852",
        "moodle": "\ue853",
        "moodle-square": "\ue854",
        "mtmt": "\ue855",
        "mtmt-square": "\ue856",
        "nakala": "\ue857",
        "nakala-square": "\ue858",
        "obp": "\ue859",
        "obp-square": "\ue85a",
        "open-access": "\ue85b",
        "open-access-square": "\ue85c",
        "open-data": "\ue85d",
        "open-data-square": "\ue85e",
        "openedition": "\ue85f",
        "openedition-square": "\ue860",
        "open-materials": "\ue861",
        "open-materials-square": "\ue862",
        "orcid": "\ue863",
        "orcid-square": "\ue864",
        "osf": "\ue865",
        "osf-square": "\ue866",
        "overleaf": "\ue867",
        "overleaf-square": "\ue868",
        "philpapers": "\ue869",
        "philpapers-square": "\ue86a",
        "piazza": "\ue86b",
        "piazza-square": "\ue86c",
        "preregistered": "\ue86d",
        "preregistered-de": "\ue86e",
        "preregistered-de-plus": "\ue86f",
        "preregistered-de-plus-square": "\ue870",
        "preregistered-de-square": "\ue871",
        "preregistered-de-tc": "\ue872",
        "preregistered-de-tc-plus": "\ue873",
        "preregistered-de-tc-plus-square": "\ue874",
        "preregistered-de-tc-square": "\ue875",
        "preregistered-square": "\ue876",
        "preregistered-tc": "\ue877",
        "preregistered-tc-plus": "\ue878",
        "preregistered-tc-plus-square": "\ue879",
        "preregistered-tc-square": "\ue87a",
        "protocols": "\ue87b",
        "protocols-square": "\ue87c",
        "psyarxiv": "\ue87d",
        "psyarxiv-square": "\ue87e",
        "publons": "\ue87f",
        "publons-square": "\ue880",
        "pubmed": "\ue881",
        "pubmed-square": "\ue882",
        "pubpeer": "\ue883",
        "pubpeer-square": "\ue884",
        // "researcherid": "\ue885",
        "researcherid-square": "\ue886",
        "researchgate": "\ue887",
        "researchgate-square": "\ue888",
        "ror": "\ue889",
        "ror-square": "\ue88a",
        "sci-hub": "\ue88b",
        "sci-hub-square": "\ue88c",
        "scirate": "\ue88d",
        "scirate-square": "\ue88e",
        "scopus": "\ue88f",
        "scopus-square": "\ue890",
        "semantic-scholar": "\ue891",
        "semantic-scholar-square": "\ue892",
        "springer": "\ue893",
        "springer-square": "\ue894",
        "ssrn": "\ue895",
        "ssrn-square": "\ue896",
        "stackoverflow": "\ue897",
        "stackoverflow-square": "\ue898",
        "viaf": "\ue899",
        "viaf-square": "\ue89a",
        "wiley": "\ue89b",
        "wiley-square": "\ue89c",
        "zenodo": "\ue89d",
        "zotero": "\ue89e",
        "zotero-square": "\ue89f",
        "usak": "\ue8a0",
        "yoksis-yazili": "\ue8a1",
        "kimlik-o": "\ue8a2",
        "destek": "\ue8a3",
        "yokakademik": "\ue8a4",

        "trdizin":"\ue801",
        "googlescholar": "\ue835",
        "scopusid": "\ue88f",
        "researcherid": "\ue819",
    };

    return <Text style={[styles.icon, style]}>{icons[name] || "?"}</Text>;
};

const styles = StyleSheet.create({
    icon: {
        fontFamily: 'AkademikIcons',
        fontSize: 20,
        color: theme.colors.acikMavi,
    },
});

export default AkademikIcons;
